apiVersion: v1
kind: ConfigMap
metadata:
  name: hoh-config
data:
  POSTGRES_HOST: "host.docker.internal"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "pre_delinquency"
  POSTGRES_USER: "admin"
  REDIS_HOST: "host.docker.internal"
  REDIS_PORT: "6379"
  CASSANDRA_HOST: "host.docker.internal"
  CASSANDRA_PORT: "9042"
  CASSANDRA_KEYSPACE: "predelinquency"
  KAFKA_HOST: "host.docker.internal"